# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97a5f8f5c37d44c5a1cd922db3e6cd1dbf445ebeffe8af186ed834296a8ba68d6e50c668ac604e14b1a2350903d4cdcc1b5968b7ea1fb644cd05d618bf8e2b99

test:
  secret_key_base: df66e67ccb4019ff678e6b096c0382bfcf562699e98e4bb1898b92e243dd96c0772f4bb7f022b990aa702134aee313c1588ecc632ea9b944f5545f6ed5ac9ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
